Airflow:
Analog Supply Voltage:
    _aliases:
        - Voltage - Supply, Analog
Architecture:
    _aliases:
        - Core Size
Battery Capacity:
    _unit: mAh
Cable Entry:
    _aliases:
        - Tab Direction
Capacitance:
    _unit: nF
Clamping Voltage:
    _unit: V
Coil Voltage:
    _unit: V
Color:
    _aliases:
        - Illumination Type, Color
        - Illumination Colour
        - Illumination Color
        - Luminous Color
        - Emitted Color
Common Pin:
    _aliases:
        - LED Polarity
Composition:
    _aliases:
        - Type
        - Product Type
Conductor Material:
Connectivity:
Connector Type:
    _aliases:
        - Product Type
        - Type
Contact Finish:
    _aliases:
        - Contact Finish - Mating
        - Contact Material
        - Contact plating
        - Contact Plating
Cross-Section:
    _unit: mm^2
Data Rate:
    _unit: b/s
Diameter:
    _aliases:
        - Industry Recognized Mating Diameter
        - Standard
    _unit: mm
Digital Supply Voltage:
    _aliases:
        - Voltage - Supply, Digital
Display Type:
Drive Type:
Dropout Voltage:
    _aliases:
        - Voltage Dropout (Max)
Duplex:
EEPROM Size:
Efficiency:
    _unit: '%'
ESR:
    _aliases:
        - ESR (Equivalent Series Resistance)
        - Equivalent Series Resistance(ESR)
        - Equivalent Series Resistance (ESR)
Filament:
FLASH Size:
    _aliases:
        - Program Memory Size
        - Memory Size
Flux Type:
Forward Voltage:
    _aliases:
        - Voltage - Forward (Vf) (Typ)
        - Voltage - Forward (Vf) (Max) @ If
        - Vf - Forward Voltage
        - Forward Voltage (Vf@If)
    _unit: V
Frequency:
    _aliases:
        - Frequency - Max
        - Frequency - Switching
        - Clock Frequency
        - Speed
        - Count Rate
        - Center Frequency
    _unit: Hz
Frequency Stability:
    _unit: ppm
Frequency Tolerance:
    _unit: ppm
    _aliases:
        - Tolerance
        - Frequency Stability
Fuse Size:
    _aliases:
        - Fuse Size / Group
Gain (dBi):
    _unit: dBi
    _aliases:
        - Gain
Gain (hFE):
    _aliases:
        - DC Current Gain (hFE) (Min) @ Ic, Vce
        - DC Current Gain (hFE@Ic,Vce)
        - DC Current Gain hFE Max
        - DC Collector/Base Gain hfe Min
Gender:
Has Switch:
    _aliases:
        - Built in Switch
        - Internal Switch(s)
        - Switch Type
        - Switch Configuration
        - With Switch
Hold Current:
    _aliases:
        - Current - Hold (Ih) (Max)
    _unit: mA
Impedance:
    _aliases:
        - Impedance @ Frequency
Inductance:
    _unit: uH
Input Offset Voltage:
    _aliases:
        - Voltage - Input Offset
        - Vos Input Offset Voltage
        - Vos - Input Offset Voltage
    _unit: mV
Input Voltage:
    _aliases:
        - Voltage - Input
        - Voltage - Input (Max)
        - Maximum Input Voltage
        - Input Voltage, Max
    _unit: V
Insulation Material:
Interface:
    _aliases:
        - Data Interface
        - Logic Type
        - Interface Type
Length:
    _unit: mm
Lens Style:
    _aliases:
        - Lens Shape
Load Capacitance:
    _unit: pF
Material:
Melting Point:
Motor Type:
    _aliases:
        - Motor Type - AC, DC
        - Motor Type - Stepper
        - Type
Mounting Type:
    _aliases:
        - Mounting Style
        - Termination Style
        - Contact Termination
Multiplexer Configuration:
    _aliases:
        - Multiplexer/Demultiplexer Circuit
Number of A/D Converters:
Number of Bits:
    _aliases:
        - Number of Bits per Element
        - Resolution (Bits)
Number of Channels:
Number of Characters:
Number of Circuits:
    _aliases:
        - Number of Elements
        - Number of Channels
        - Number of Gates
        - Elements per Chip
Number of Conductors:
Number of Contacts:
    _aliases:
        - Number of Positions
        - Number of Positions or Pins (Grid)
        - Number of Tie Points (Total)
        - Number of contacts points
        - Number of pins
        - Number of Positions / Contacts per Port
        - Number of PINs Per Row
Number of D/A Converters:
Number of Drivers/Receivers:
    _aliases:
        - Driver/receiver
Number of IO Pins:
    _aliases:
        - Number of I/O
        - Number of I/Os
Number of Positions:
Number of Rows:
Number of Turns:
    _aliases:
        - Turns
        - Assembly
On Resistance:
    _aliases:
        - Resistance - RDS(On)
        - Rds On (Max) @ Id, Vgs
        - On-State Resistance (Max)
        - Rds On - Drain-Source Resistance
Operating Force:
Output Current:
    _aliases:
        - Current - Output
        - Current - Output Source/Sink
        - Current - Output (Max)
        - Current - Output / Channel
        - Current - Output High, Low
        - Output Current (Max)
    _unit: A
Output Supply Current:
    _aliases:
        - Output Current per Channel
    _unit: mA
Output Polarity:
    _aliases:
        - Output Configuration
        - Polarity
Output Type:
Output Voltage:
    _aliases:
        - Voltage - Output (Min/Fixed)
        - Voltage - Output 1
    _unit: V
Package Type:
    _aliases:
        - Package / Case
        - Termination Style
        - Mounting form
        - Case Code - in
        - Packaging
Pitch:
    _aliases:
        - Pitch - Mating
        - Contacts pitch
    _unit: mm
Plating:
Polarization:
Processor Type:
    _aliases:
        - Core Processor
Propagation Delay Time:
    _unit: ns
Protocol:
    _aliases:
        - Product
Pulses per Revolution:
    _aliases:
        - Resolution
RAM Size:
Rated Current:
    _aliases:
        - Current Rating
        - Current Rating (Amps)
        - Current Rating (Max)
        - Current - Average Rectified (Io)
        - Current - Average Rectified (Io) (per Diode)
        - Current - Collector (Ic) (Max)
        - Contact Rating @ Voltage
        - Current - Continuous Drain (Id) @ 25°C
        - Contact Rating
        - Current Rating (DC)
        - Current Rating (AC)
        - Collector Current (Ic)
        - Current - DC Forward (If) (Max)
        - Contact Current
        - Id - Continuous Drain Current
        - Ipp - Peak Pulse Current
        - Maximum DC Current
        - If - Forward Current
        - Maximum DC Collector Current
        - Continuous Collector Current
    _unit: A
Rated Power:
    _aliases:
        - Power (Watts)
        - Power - Max
        - Power Rating
        - Power(Watts)
        - Power Dissipation
        - Power Dissipation (Pd)
        - Power per Element
        - Nominal load
        - Pd - Power Dissipation
    _unit: W
Rated Voltage:
    _aliases:
        - Voltage - Rated
        - Voltage Rated
        - Voltage - Max
        - Voltage Rating
        - Voltage Rating DC
        - Voltage Rating - DC
        - Voltage Rating (DC)
        - Voltage Rating AC
        - Voltage Rating - AC
        - Voltage Rating (AC)
        - Voltage Rating (Max)
        - Voltage - Collector Emitter Breakdown (Max)
        - Collector-Emitter Breakdown Voltage (Vceo)
        - Collector-Emitter Voltage VCEO Max
        - Collector- Emitter Voltage VCEO Max
        - Drain to Source Voltage (Vdss)
        - Vds - Drain-Source Breakdown Voltage
        - Voltage - Breakdown (V(BR)GSS)
        - Voltage - Load
        - Nominal voltage
        - Maximum Voltage
        - Load Voltage Rating
        - Operating Voltage (Max)
        - Supply Voltage
    _unit: V
Reference Type:
Resistance:
    _aliases:
        - Resistance (Ohms)
        - DC Resistance (DCR) (Max)
        - Resistor
        - Resistor Values
        - DC Resistance
    _unit: ohm
Reverse Breakdown Voltage:
    _aliases:
        - Voltage - DC Reverse (Vr) (Max)
        - Voltage - Zener (Nom) (Vz)
        - Zener Voltage (Nom)
        - Vr - Reverse Voltage
        - Peak Reverse Voltage
        - Breakdown Voltage
    _unit: V
Rotation Angle:
    _aliases:
        - Rotation
    _unit: °
Sampling Rate:
    _aliases:
        - Sampling Rate (Per Second)
    _unit: Hz
Settling Time:
    _unit: us
Shaft Type:
Shaft Size:
    _unit: mm
Shape:
Shrouding:
Size:
    _aliases:
        - Size / Dimension
        - Lens Size
        - Package / Case
        - Case Code - in
Slew Rate:
    _unit: V/us
    _aliases:
        - SR - Slew Rate
Speed:
Standard:
Supply Current:
    _aliases:
        - Current - Supply
        - Output Current per Channel
        - Low Level Output Current
    _unit: mA
Supply Voltage:
    _aliases:
        - Voltage - Supply
        - Voltage - Supply Span (Max)
        - Voltage - Supply (Vcc/Vdd)
        - Voltage - Supply, Single (V+)
        - Voltage - Supply, Dual (V±)
        - Supply Voltage - Max
Switch Time:
    _aliases:
        - Switch Time (Ton, Toff) (Max)
Switch Type:
    _aliases:
        - Circuit
        - Circuit per Deck
        - Switch Circuit
        - Switch Function
        - Contact Form
Taper:
Temperature Coefficient:
    _aliases:
        - Class
Thread Size:
Tolerance:
    _unit: '%'
Time to Trip:
    _aliases:
        - Maximum Time to Trip
    _unit: ms
Travel Range:
    _aliases:
        - Travel
    _unit: mm
Trip Current:
    _aliases:
        - Current - Trip (It)
    _unit: mA
Type:
    _aliases:
        - Topology
        - Logic Type
Wavelength:
    _aliases:
        - Wavelength - Dominant
        - Wavelength/Colour Temperature
        - Wavelength/Color Temperature
        - Wavelength - Peak
        - Dominant Wavelength
    _unit: nm
Working Voltage:
    _aliases:
        - Maximum DC Volts
        - Voltage - Reverse Standoff (Typ)
    _unit: V
Transistor Polarity:
